# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x06orders\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n\x05Order\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x1e\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x0e.orders.Action\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12-\n\torderTime\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x63ustID\x18\x05 \x01(\t*\x1b\n\x06\x41\x63tion\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01\x62\x06proto3')

_ACTION = DESCRIPTOR.enum_types_by_name['Action']
Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
BUY = 0
SELL = 1


_ORDER = DESCRIPTOR.message_types_by_name['Order']
Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:orders.Order)
  })
_sym_db.RegisterMessage(Order)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTION._serialized_start=195
  _ACTION._serialized_end=222
  _ORDER._serialized_start=57
  _ORDER._serialized_end=193
# @@protoc_insertion_point(module_scope)
